from models import db, Car, CarReview, CrashTest
from db_config import SQLALCHEMY_DATABASE_URI
from flask import Flask
from simple_server import app

CARS = [car for car in [
    {
        "make": "Audi",
        "model": "Q7",
        "year": 2022,
        "price": 5900000,
        "body_type": "Внедорожник 5 дв.",
        "engine_type": "2.0 л / 252 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Чёрный",
        "mileage": 9000,
        "generation": "II (4M) Рестайлинг",
        "generation_url": "https://auto.ru/catalog/cars/audi/q7/4m-fl/",
        "trim": "45 TFSI quattro tiptronic",
        "trim_url": "https://auto.ru/catalog/cars/audi/q7/4m-fl/20478112/",
        "tax": "37 800 ₽ / год",
        "drivetrain": "Полный",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "2 года и 5 месяцев",
        "customs": "Растаможен",
        "vin": "WA1ZZZ4M7ND123456",
        "city": "Санкт-Петербург",
        "dealer": "Профессиональный продавец",
        "images": [
            "/static/images/cars/audi_q7_1.jpg",
            "/static/images/cars/audi_q7_2.jpg",
            "/static/images/cars/audi_q7_3.jpg",
            "/static/images/cars/audi_q7_4.jpg",
            "/static/images/cars/audi_q7_5.jpg",
            "/static/images/cars/audi_q7_6.jpg",
            "/static/images/cars/audi_q7_7.jpg",
            "/static/images/cars/audi_q7_8.jpg",
            "/static/images/cars/audi_q7_9.jpg"
        ],
        "description": "Audi Q7 45 TFSI quattro tiptronic, 2022 года выпуска, в отличном состоянии. Один владелец, оригинальный ПТС, полный комплект ключей. Богатая комплектация, все ТО у дилера."
    },
    {
        "make": "Toyota",
        "model": "Camry",
        "year": 2021,
        "price": 2450000,
        "body_type": "Седан",
        "engine_type": "2.5 л / 200 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Белый",
        "mileage": 18000,
        "generation": "VIII (XV70) Рестайлинг",
        "generation_url": "https://auto.ru/catalog/cars/toyota/camry/xv70-fl/",
        "trim": "2.5L Prestige Safety",
        "trim_url": "https://auto.ru/catalog/cars/toyota/camry/xv70-fl/20478112/",
        "tax": "7 800 ₽ / год",
        "drivetrain": "Передний",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "1 год и 8 месяцев",
        "customs": "Растаможен",
        "vin": "JTNBF3HK203123456",
        "city": "Москва",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/camry_1.jpg",
            "/static/images/cars/camry_2.jpg",
            "/static/images/cars/camry_3.jpg"
        ],
        "description": "Toyota Camry 2.5L Prestige Safety, 2021 года, белый цвет, один владелец, оригинальный ПТС, отличное состояние, все ТО у дилера."
    },
    {
        "make": "Kia",
        "model": "Rio",
        "year": 2021,
        "price": 1100000,
        "body_type": "Седан",
        "engine_type": "1.6 л / 123 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Серый",
        "mileage": 32000,
        "generation": "IV (YB) Рестайлинг",
        "generation_url": "https://auto.ru/catalog/cars/kia/rio/yb-fl/",
        "trim": "1.6 AT Luxe",
        "trim_url": "https://auto.ru/catalog/cars/kia/rio/yb-fl/20478112/",
        "tax": "3 696 ₽ / год",
        "drivetrain": "Передний",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "2 года",
        "customs": "Растаможен",
        "vin": "Z94C241BBMR123456",
        "city": "Казань",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/rio_1.jpg",
            "/static/images/cars/rio_2.jpg"
        ],
        "description": "Kia Rio 1.6 AT Luxe, 2021 года, серый цвет, один владелец, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Hyundai",
        "model": "Solaris",
        "year": 2022,
        "price": 1200000,
        "body_type": "Седан",
        "engine_type": "1.6 л / 123 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Синий",
        "mileage": 15000,
        "generation": "II (HC) Рестайлинг",
        "generation_url": "https://auto.ru/catalog/cars/hyundai/solaris/hc-fl/",
        "trim": "1.6 AT Comfort",
        "trim_url": "https://auto.ru/catalog/cars/hyundai/solaris/hc-fl/20478112/",
        "tax": "3 696 ₽ / год",
        "drivetrain": "Передний",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "1 год",
        "customs": "Растаможен",
        "vin": "Z94K241CBMR123456",
        "city": "Екатеринбург",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/solaris_1.jpg",
            "/static/images/cars/solaris_2.jpg"
        ],
        "description": "Hyundai Solaris 1.6 AT Comfort, 2022 года, синий цвет, один владелец, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Volkswagen",
        "model": "Passat",
        "year": 2018,
        "price": 1700000,
        "body_type": "Седан",
        "engine_type": "1.8 л / 180 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Серебристый",
        "mileage": 54000,
        "generation": "B8",
        "generation_url": "https://auto.ru/catalog/cars/volkswagen/passat/b8/",
        "trim": "1.8 TSI DSG",
        "trim_url": "https://auto.ru/catalog/cars/volkswagen/passat/b8/20478112/",
        "tax": "6 300 ₽ / год",
        "drivetrain": "Передний",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "2 владельца",
        "pts": "Оригинал",
        "ownership_period": "3 года",
        "customs": "Растаможен",
        "vin": "WVWZZZ3CZJE123456",
        "city": "Новосибирск",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/passat_1.jpg",
            "/static/images/cars/passat_2.jpg"
        ],
        "description": "Volkswagen Passat 1.8 TSI DSG, 2018 года, серебристый цвет, два владельца, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Lada",
        "model": "Vesta",
        "year": 2021,
        "price": 950000,
        "body_type": "Седан",
        "engine_type": "1.6 л / 113 л.с. / Бензин",
        "transmission": "Механическая",
        "fuel_type": "Бензин",
        "color": "Красный",
        "mileage": 21000,
        "generation": "I",
        "generation_url": "https://auto.ru/catalog/cars/lada/vesta/i/",
        "trim": "1.6 MT Comfort",
        "trim_url": "https://auto.ru/catalog/cars/lada/vesta/i/20478112/",
        "tax": "2 034 ₽ / год",
        "drivetrain": "Передний",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "1 год и 3 месяца",
        "customs": "Растаможен",
        "vin": "XTA218450M1234567",
        "city": "Самара",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/vesta_1.jpg",
            "/static/images/cars/vesta_2.jpg"
        ],
        "description": "Lada Vesta 1.6 MT Comfort, 2021 года, красный цвет, один владелец, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Mercedes-Benz",
        "model": "C-Class",
        "year": 2020,
        "price": 3200000,
        "body_type": "Седан",
        "engine_type": "2.0 л / 197 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Чёрный",
        "mileage": 27000,
        "generation": "W205 Рестайлинг",
        "generation_url": "https://auto.ru/catalog/cars/mercedes-benz/c_klasse/w205-fl/",
        "trim": "C 200 4MATIC",
        "trim_url": "https://auto.ru/catalog/cars/mercedes-benz/c_klasse/w205-fl/20478112/",
        "tax": "8 880 ₽ / год",
        "drivetrain": "Полный",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "2 года",
        "customs": "Растаможен",
        "vin": "WDDWF8EB1LR123456",
        "city": "Москва",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/cclass_1.jpg",
            "/static/images/cars/cclass_2.jpg"
        ],
        "description": "Mercedes-Benz C-Class C 200 4MATIC, 2020 года, чёрный цвет, один владелец, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Audi",
        "model": "A4",
        "year": 2019,
        "price": 2100000,
        "body_type": "Седан",
        "engine_type": "2.0 л / 190 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Белый",
        "mileage": 35000,
        "generation": "B9",
        "generation_url": "https://auto.ru/catalog/cars/audi/a4/b9/",
        "trim": "2.0 TFSI S tronic",
        "trim_url": "https://auto.ru/catalog/cars/audi/a4/b9/20478112/",
        "tax": "7 600 ₽ / год",
        "drivetrain": "Передний",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "2 владельца",
        "pts": "Оригинал",
        "ownership_period": "2 года",
        "customs": "Растаможен",
        "vin": "WAUZZZF43KA123456",
        "city": "Санкт-Петербург",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/a4_1.jpg",
            "/static/images/cars/a4_2.jpg"
        ],
        "description": "Audi A4 2.0 TFSI S tronic, 2019 года, белый цвет, два владельца, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Kia",
        "model": "Sportage",
        "year": 2022,
        "price": 2700000,
        "body_type": "Внедорожник 5 дв.",
        "engine_type": "2.0 л / 150 л.с. / Бензин",
        "transmission": "Автоматическая",
        "fuel_type": "Бензин",
        "color": "Серый",
        "mileage": 12000,
        "generation": "IV (QL) Рестайлинг",
        "generation_url": "https://auto.ru/catalog/cars/kia/sportage/ql-fl/",
        "trim": "2.0 AT Luxe",
        "trim_url": "https://auto.ru/catalog/cars/kia/sportage/ql-fl/20478112/",
        "tax": "4 500 ₽ / год",
        "drivetrain": "Полный",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "1 год",
        "customs": "Растаможен",
        "vin": "XWEWKH81BMM123456",
        "city": "Краснодар",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/sportage_1.jpg",
            "/static/images/cars/sportage_2.jpg"
        ],
        "description": "Kia Sportage 2.0 AT Luxe, 2022 года, серый цвет, один владелец, оригинальный ПТС, отличное состояние."
    },
    {
        "make": "Toyota",
        "model": "RAV4",
        "year": 2021,
        "price": 3000000,
        "body_type": "Внедорожник 5 дв.",
        "engine_type": "2.0 л / 149 л.с. / Бензин",
        "transmission": "Вариатор",
        "fuel_type": "Бензин",
        "color": "Белый",
        "mileage": 17000,
        "generation": "V (XA50)",
        "generation_url": "https://auto.ru/catalog/cars/toyota/rav4/x50/",
        "trim": "2.0 CVT AWD Prestige",
        "trim_url": "https://auto.ru/catalog/cars/toyota/rav4/x50/20478112/",
        "tax": "4 350 ₽ / год",
        "drivetrain": "Полный",
        "steering": "Левый",
        "condition": "Не требует ремонта",
        "owners": "1 владелец",
        "pts": "Оригинал",
        "ownership_period": "1 год и 2 месяца",
        "customs": "Растаможен",
        "vin": "JTM6WRFV40D123456",
        "city": "Москва",
        "dealer": "Официальный дилер",
        "images": [
            "/static/images/cars/rav4_1.jpg",
            "/static/images/cars/rav4_2.jpg"
        ],
        "description": "Toyota RAV4 2.0 CVT AWD Prestige, 2021 года, белый цвет, один владелец, оригинальный ПТС, отличное состояние."
    }
] if not ((car['make'] == 'Toyota' and car['model'] == 'Camry') or (car['make'] == 'BMW' and car['model'] == '3 Series'))]

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db.init_app(app)

with app.app_context():
    db.session.query(Car).delete()  # Очистить таблицу перед импортом (опционально)
    for car_data in CARS:
        car = Car(
            make=car_data['make'],
            model=car_data['model'],
            year=car_data['year'],
            price=car_data['price'],
            body_type=car_data.get('body_type'),
            engine_type=car_data.get('engine_type'),
            transmission=car_data.get('transmission'),
            fuel_type=car_data.get('fuel_type'),
            color=car_data.get('color'),
            generation=car_data.get('generation'),
            generation_url=car_data.get('generation_url'),
            trim=car_data.get('trim'),
            trim_url=car_data.get('trim_url'),
            tax=car_data.get('tax'),
            drivetrain=car_data.get('drivetrain'),
            steering=car_data.get('steering'),
            condition=car_data.get('condition'),
            owners=car_data.get('owners'),
            pts=car_data.get('pts'),
            ownership_period=car_data.get('ownership_period'),
            customs=car_data.get('customs'),
            vin=car_data.get('vin'),
            city=car_data.get('city'),
            dealer=car_data.get('dealer'),
            mileage=car_data.get('mileage'),
            images=car_data.get('images'),
            description=car_data.get('description')
        )
        db.session.add(car)
    db.session.commit()
print("Импорт завершён!") 